### PR TITLE
controls colored lightbulbs

### LINKED ISSUE #14: Control light color
Does Tuya's API provide the ability to also change a light's color instead of only on/off and dimming? I'd like to contribute some code 🤔

### PR DESCRIPTION
**Pull request by niksauer**
to close #14 
has been tested with "Solmore Smart LED Strip Light" (Amazon: https://www.amazon.de/gp/product/B07PV6ZKPW/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1)

### CODE REVIEW

**Comment by Torac2** [comment]
What method are you sending to change hue saturation etc?

**Comment by Torac2** [comment]
Just tested:
[SET][RGBC Smart Bulb ] Characteristic.Saturation Error: Error: Could not parse json. Body:
When trying to control it.

**Comment by niksauer** [comment]
```
color {
  brightness: number;
  saturation: number;
  hue: number;
}

tuyaWebApi.setDeviceState(this.deviceId, 'colorSet', { color: color })
```

i've modified the `tuyaWebApi.setDeviceState` method to accept an object that will be used as the requests payload. by such, it works for both state/brightness requests (`{ value: value }`) and color setting.

**Comment by Torac2** [comment]
[2019-8-12 14:41:35] [TuyaWebPlatform] [SET][RGBC Smart Bulb ] Characteristic.Brightness Error: Error: Could not parse json. Body: 
[2019-8-12 14:41:35] ReferenceError: value is not defined
    at TuyaWebApi.getDeviceState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:102:18)
    at Characteristic.LightAccessory.service.getCharacteristic.on.callback (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:118:36)
    at emitThree (events.js:135:13)
    at Characteristic.emit (events.js:216:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at emitMany (events.js:146:13)
    at HAPServer.emit (events.js:223:7)

Im getting this error right now.
Thanks @niksauer

**Comment by basdelfos** [comment]
Thanks for the work and time you put into this. From looking at the code submitted it seems oke, only concern I have is if the other devices still work after the changes made to the API wrapper. I will regression test your PR as soon as possible. I can not test with RGB led strip or light bulb, but will test if the outlets and dimmer still work. When successful I will merge your PR.

**Comment by niksauer** [comment]
> [2019-8-12 14:41:35] [TuyaWebPlatform] [SET][RGBC Smart Bulb ] Characteristic.Brightness Error: Error: Could not parse json. Body:
Could you please update your `sendRequestJson` method in `tuyawebapi.js` to be: 

```
sendRequestJson(url, body, method, callbackSuccess, callbackError) {
    this.log(JSON.stringify(body));
    
    this.sendRequest(url, body, method,
      (response, body) => {
        this.log(JSON.stringify(body));
        
        try {
          const obj = JSON.parse(body);
          callbackSuccess(response, obj);
        }
        catch (error) {
          callbackError(new Error(`Could not parse json. Body: ${body}`, error));
        }
      },
      (error) => {
        callbackError(error);
      }
    );
  }
```

Then we can inspect your specific request/response 🙂 Mine look like this:

```
[SET][Characteristic.On]
{"header":{"name":"turnOnOff","namespace":"control","payloadVersion":1},"payload":{"value":1,"accessToken":"","devId":""}}

[SET][Characteristic.Brightness]
{"header":{"name":"brightnessSet","namespace":"control","payloadVersion":1},"payload":{"value":100,"accessToken":"","devId":""}}

[SET][Characteristic.Saturation/Hue]
{"header":{"name":"colorSet","namespace":"control","payloadVersion":1},"payload":{"color":{"brightness":100,"saturation":255,"hue":198},"accessToken":"","devId":""}}
```


> [2019-8-12 14:41:35] ReferenceError: value is not defined
> at TuyaWebApi.getDeviceState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:102:18)
> at Characteristic.LightAccessory.service.getCharacteristic.on.callback (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:118:36)

This error doesn't make sense since neither my nor the previous version of `getDeviceState` depend on a `value` variable..

@basdelfos I'll push another commit shortly to update the payload for the other devices and test files. Forgot to pass an object `{ value: X}` to the API wrapper instead of the plain value.

**Comment by basdelfos** [comment]
Hi,

Did a test today and it seems that my dimmers are also recognised as lights now, and as the dimmer doesn't have saturation, I now get an error in the log. I will take a look at this.

image

**Comment by niksauer** [comment]
Sorry, haven't had the chance to make any changes in the meantime. Looks like you merged the PR nevertheless. Were you able to fix your dimmer?

**Comment by basdelfos** [comment]
No problem, I fixed by adding the option to overrule the device type in the config.

**Pull request merged**
